### ISSUE TITLE
Feature Request: Server Pack

### ISSUE THREAD

**Issue by diauweb** [KEYboradManDesu/Create-Above-and-Beyond-Community-Refresh#1]

**Comment by Gl0w1amp** [comment]
Server pack is in progress and we will add it in the next release.

**Comment by Gl0w1amp** [comment]
The server pack has been uploaded.

**Comment by diauweb** [comment]
> The server pack has been uploaded.

Where can I find it?

**Comment by Gl0w1amp** [comment]
You now can find it in Release.
